### ISSUE TITLE
Random seed

### ISSUE THREAD

**Issue by nastaranj** [datamole-ai/active-semi-supervised-clustering#1]
The results of the clustering (e.g., COP-KMeans, PC-KMeans) are not reproducible. As a solution, it is recommended to pass a parameter to the function in order to set the random seed.

**Comment by magicalJohn** [comment]
I think you can make the results reproducible by setting the seed of numpy and the random python module. (I am not sure that the second one is necessary) 
```
    np.random.seed(4321)
    random.seed(4321)
```
